name: Vivliostyle build in Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag my-image
      - run: docker run --rm --env PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright --cap-add=SYS_ADMIN -w /app -v $(pwd):/app my-image sh build.sh
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./詩晒古　第二号.pdf
          asset_name: 詩晒古　第二号.pdf
          asset_content_type: application/pdf
