name: Vivliostyle build in Docker
# read and write permissionが必要
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag my-image
      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo" # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      - run: docker run --rm --env PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright --env GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} --env GITHUB_REPOSITORY=${GITHUB_REPOSITORY} --env GITHUB_SHA=${GITHUB_SHA} --env CURRENT_DATETIME=${CURRENT_DATETIME} --cap-add=SYS_ADMIN -w /app -v $(pwd):/app my-image bash build_upload.sh
